version: '3'

services:
  sunbookApp:
    image: sunbook
    volumes:
      - /home/ubuntu/jenkins_home/workspace/sunbook/build/libs:/usr/src/app
    ports:
      - "8082:8080"
    environment:
      - TZ=Asia/Seoul
networks:
  default:
    external:
      name: mydb