spring:
    profiles:
        active: default
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: 11111111
        url: jdbc:mysql://localhost:3306/sunbook?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
        username: sunshine
    devtools:
        livereload:
            enabled: true
    freemarker:
        cache: false
    jpa:
        database: mysql
        database-platform: org.hibernate.dialect.MySQL5Dialect
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
                format_sql: true
        show-sql: true

---

spring:
    profiles: deploy
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: 11111111
        url: jdbc:mysql://sunbook:3306/sunbook?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
        username: sunshine
    jpa:
        database: mysql
        database-platform: org.hibernate.dialect.MySQL5Dialect
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
                format_sql: true
        show-sql: true
cloud:
    aws:
        s3:
            bucket: sunbook
        region:
            static: ap-northeast-2
        stack:
            auto: false